"""Drinks fix

Revision ID: 41893c32f321
Revises: 
Create Date: 2024-02-06 18:47:08.969747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41893c32f321'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desert_id'), 'desert', ['id'], unique=False)
    op.drop_table('dessert')
    op.create_index(op.f('ix_cafe_description'), 'cafe', ['description'], unique=False)
    op.create_index(op.f('ix_cafe_id'), 'cafe', ['id'], unique=False)
    op.create_index(op.f('ix_cafe_name'), 'cafe', ['name'], unique=False)
    op.alter_column('coffee', 'location',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_coffee_description'), 'coffee', ['description'], unique=False)
    op.create_index(op.f('ix_coffee_id'), 'coffee', ['id'], unique=False)
    op.create_index(op.f('ix_coffee_location'), 'coffee', ['location'], unique=False)
    op.create_index(op.f('ix_coffee_name'), 'coffee', ['name'], unique=False)
    op.alter_column('drinks', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('fk_drinks_cafe_idx', table_name='drinks')
    op.create_index(op.f('ix_drinks_description'), 'drinks', ['description'], unique=False)
    op.create_index(op.f('ix_drinks_id'), 'drinks', ['id'], unique=False)
    op.create_index(op.f('ix_drinks_name'), 'drinks', ['name'], unique=False)
    op.alter_column('favorite', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('fk_favorite_cafe1_idx', table_name='favorite')
    op.drop_index('fk_favorite_user1_idx', table_name='favorite')
    op.create_index(op.f('ix_favorite_id'), 'favorite', ['id'], unique=False)
    op.alter_column('order', 'total_price',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('order', 'count',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('order', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order', 'drinks_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order', 'coffee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('order', 'weight_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('fk_order_cafe1_idx', table_name='order')
    op.drop_index('fk_order_coffee1_idx', table_name='order')
    op.drop_index('fk_order_drinks1_idx', table_name='order')
    op.drop_index('fk_order_weight1_idx', table_name='order')
    op.create_index(op.f('ix_order_count'), 'order', ['count'], unique=False)
    op.create_index(op.f('ix_order_drink_type'), 'order', ['drink_type'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_total_price'), 'order', ['total_price'], unique=False)
    op.alter_column('products', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('products', 'drinks_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('products', 'coffee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('products', 'desert_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('fk_products_cafe1_idx', table_name='products')
    op.drop_index('fk_products_coffee1_idx', table_name='products')
    op.drop_index('fk_products_desert1_idx', table_name='products')
    op.drop_index('fk_products_drinks1_idx', table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_constraint('fk_products_desert1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'desert', ['desert_id'], ['id'])
    op.alter_column('rating', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('rating', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('fk_rating_cafe1_idx', table_name='rating')
    op.drop_index('fk_rating_user1_idx', table_name='rating')
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    op.create_index(op.f('ix_rating_rating'), 'rating', ['rating'], unique=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.alter_column('weight', 'price',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('weight', 'coffee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('weight', 'drinks_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('fk_weight_coffee1_idx', table_name='weight')
    op.drop_index('fk_weight_drinks1_idx', table_name='weight')
    op.create_index(op.f('ix_weight_id'), 'weight', ['id'], unique=False)
    op.create_index(op.f('ix_weight_price'), 'weight', ['price'], unique=False)
    op.create_index(op.f('ix_weight_weight'), 'weight', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_weight'), table_name='weight')
    op.drop_index(op.f('ix_weight_price'), table_name='weight')
    op.drop_index(op.f('ix_weight_id'), table_name='weight')
    op.create_index('fk_weight_drinks1_idx', 'weight', ['drinks_id'], unique=False)
    op.create_index('fk_weight_coffee1_idx', 'weight', ['coffee_id'], unique=False)
    op.alter_column('weight', 'drinks_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('weight', 'coffee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('weight', 'price',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.drop_index(op.f('ix_rating_rating'), table_name='rating')
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.create_index('fk_rating_user1_idx', 'rating', ['user_id'], unique=False)
    op.create_index('fk_rating_cafe1_idx', 'rating', ['cafe_id'], unique=False)
    op.alter_column('rating', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('rating', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_desert1', 'products', 'dessert', ['desert_id'], ['id'])
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index('fk_products_drinks1_idx', 'products', ['drinks_id'], unique=False)
    op.create_index('fk_products_desert1_idx', 'products', ['desert_id'], unique=False)
    op.create_index('fk_products_coffee1_idx', 'products', ['coffee_id'], unique=False)
    op.create_index('fk_products_cafe1_idx', 'products', ['cafe_id'], unique=False)
    op.alter_column('products', 'desert_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('products', 'coffee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('products', 'drinks_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('products', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_order_total_price'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_drink_type'), table_name='order')
    op.drop_index(op.f('ix_order_count'), table_name='order')
    op.create_index('fk_order_weight1_idx', 'order', ['weight_id'], unique=False)
    op.create_index('fk_order_drinks1_idx', 'order', ['drinks_id'], unique=False)
    op.create_index('fk_order_coffee1_idx', 'order', ['coffee_id'], unique=False)
    op.create_index('fk_order_cafe1_idx', 'order', ['cafe_id'], unique=False)
    op.alter_column('order', 'weight_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('order', 'coffee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('order', 'drinks_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('order', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('order', 'count',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('order', 'total_price',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.drop_index(op.f('ix_favorite_id'), table_name='favorite')
    op.create_index('fk_favorite_user1_idx', 'favorite', ['user_id'], unique=False)
    op.create_index('fk_favorite_cafe1_idx', 'favorite', ['cafe_id'], unique=False)
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorite', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_drinks_name'), table_name='drinks')
    op.drop_index(op.f('ix_drinks_id'), table_name='drinks')
    op.drop_index(op.f('ix_drinks_description'), table_name='drinks')
    op.create_index('fk_drinks_cafe_idx', 'drinks', ['cafe_id'], unique=False)
    op.alter_column('drinks', 'cafe_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_coffee_name'), table_name='coffee')
    op.drop_index(op.f('ix_coffee_location'), table_name='coffee')
    op.drop_index(op.f('ix_coffee_id'), table_name='coffee')
    op.drop_index(op.f('ix_coffee_description'), table_name='coffee')
    op.alter_column('coffee', 'location',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.drop_index(op.f('ix_cafe_name'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_id'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_description'), table_name='cafe')
    op.create_table('dessert',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_desert_id'), table_name='desert')
    op.drop_table('desert')
    # ### end Alembic commands ###
